import "@/styles/globals.css";

//Import Bitter as the font here. - Sarah
//1- Import the fonts we want

// import { Inter } from "next/font/google";
import { Bitter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "sonner";
import FlowProvider from "./testlayout";

//2 Do this for Bitter
// https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

const bitter = Bitter({
  subsets: ["latin"], 
  variable: "--font-serif",
})


export const metadata = {
  title: "Amaxa Impact",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo.png" }],
};

export default function RootLayout({
  children,
  modal
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {

//3 Input Bitter instead - line 41
// Question for you to investigate: the CSS before ${inter.variable} - what are the options to write in, what do they mean...
// <body className={`font-sans ${inter.variable}`}>

// Theme provider: how we change the theme in CSS (don't need to change this to change font initially)

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-serif ${bitter.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>
            <div className="flex h-screen">
              <Sidebar />
              <main className="flex-1 overflow-y-auto p-8 pt-2 md:p-8 bg-background">
                <FlowProvider>
                  {children}
                </FlowProvider>
                <Toaster position="top-center" richColors />
              </main>
            </div>
            {modal}
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
